baseURL = "https://pzs70.github.io/HugoStaticTest/"
languageCode = "hu"
title = "Saját Oldalam"
theme = "hextra"

[params]
  cookiebotId = "546123a5-a439-4043-b475-4df2f3821ea0"
[params.search]
  enable = true #

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/felhasznaloneved"
  weight = 30

[[menu.main]]
  name = "Dokumentáció"
  identifier = "docs"
  url = "/docs/"
  weight = 10

[[menu.main]]
  name = "AI-901"
  parent = "docs"
  url = "/docs/ai-901/"
  weight = 1

[[menu.main]]
  name = "Blog"
  identifier = "blog"
  url = "/blog/"
  weight = 20

